### ISSUE TITLE
Add documentation on creating mbtiles

### ISSUE THREAD

**Issue by jessbeutler** [hotosm/toolbox#3]

**Comment by PaulUithol** [comment]
Including a quick guide on what data to include on your mbtiles/background
layer.

Technical options to document:

- Tilemill
- Ivan's scripts (to find and assess)
- tl (see @mojodna's repo's, will find link)
- what else?

~ sent from mobile

**Comment by jessbeutler** [comment]
Added with upload of https://toolbox.hotosm.org/pages/data-collection-and-field-mapping/3.2.2_setting_up_omk/
