### ISSUE TITLE
Numbered lists not rendering

### ISSUE THREAD

**Issue by jessbeutler** [hotosm/toolbox#5]
Numbered lists appear in preview correctly but do not render properly in the actual site. 
Content location: https://github.com/hotosm/toolbox/blob/master/content/pages/data-use-and-analysis/7.1.1-Installing-QGIS.md <br>
<b>Github preview</b> 
![image](https://user-images.githubusercontent.com/36767434/60212759-f999c580-982f-11e9-9f25-06b4ffa43294.png)
<br><br>
<b>Site Rendering</b>
![image](https://user-images.githubusercontent.com/36767434/60212861-3cf43400-9830-11e9-8f9e-80c4b403c349.png)

**Comment by russbiggs** [comment]
for both ordered lists and unordered lists prefer a markdown line break instead of a <br> element.  Markdown lists also need a line break before them e.g.:
```md
To install from a shared file:<br>
1. Go to folder shared to you and downloaded to your computer.
2. Select the appropriate installer folder based on your operating system (Windows 32-bit; Windows 64-bit; or Mac). 
3. Open the installer to begin the installation process. 
```

should be:

```md
To install from a shared file:

1. Go to folder shared to you and downloaded to your computer.
2. Select the appropriate installer folder based on your operating system (Windows 32-bit; Windows 64-bit; or Mac). 
3. Open the installer to begin the installation process. 
```

**Comment by jessbeutler** [comment]
Thanks, Russ! Realized it was a markdown error after a while, but this is helpful. :)
